FROM nginx:latest

#COPY html /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf

COPY default.conf /etc/nginx/conf.d

# ENV DOCKERIZE_VERSION v0.7.0

# RUN apt-get update
# RUN apt-get install -y wget
# RUN wget -O - https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz | tar xzf - -C /usr/local/bin
# RUN apt-get autoremove -yqq --purge wget 
# RUN rm -rf /var/lib/apt/lists/*


ENTRYPOINT [ "/docker-entrypoint.sh" ]
CMD ["nginx", "-g", "daemon off;"]